{% set version = "1.1.7" %}
{% set name = "BiG-SCAPE" %}
{% set sha256 = "91e4065a655f217635940caf71144389ed877dbc8b4c1fe5c8a507d2c5f1b9d4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/medema-group/BiG-SCAPE/archive/refs/tags/v{{ version }}.tar.gz
  sha256: {{ sha256 }}
  
build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - python
    - pip
  run:
   - python
   - numpy
   - scipy
   - biopython
   - scikit-learn=0.19.1
   - networkX>=2.0
   - fasttrees
   - hmmer

test:
  commands:
    - python --version
    - pip show scikit-learn

about:
  home: https://github.com/medema-group/BiG-SCAPE
  lincense: GNU Affero v3
  lincense_file: LINCENSE
  summary: "Construct sequence similarity networks of Biosynthetic Gene Clusters (BGCs) and groups them into Gene Cluster Families (GCFs)."