var run_data={
    "duration":"0h25m9s",
    "end_time":"07/02/2024 16:04:31",
    "input":{
        "accession":[
            {
                "id":"genome_0",
                "label":"AP018533.1"
            },
            {
                "id":"genome_1",
                "label":"Actinomadura kijaniata"
            },
            {
                "id":"genome_2",
                "label":"Streptomyces griseus subsp. griseus NBRC 13350"
            },
            {
                "id":"genome_3",
                "label":"Streptomyces coelicolor A3(2)"
            },
            {
                "id":"genome_4",
                "label":"Catenulispora acidiphila DSM 44928"
            },
            {
                "id":"genome_5",
                "label":"Streptomyces rishiriensis"
            },
            {
                "id":"genome_6",
                "label":"Staphylococcus aureus subsp. aureus NCTC 8325"
            },
            {
                "id":"genome_7",
                "label":"Streptomyces sp. RM-5-8"
            },
            {
                "id":"genome_8",
                "label":"Hahella chejuensis"
            },
            {
                "id":"genome_9",
                "label":"Epichloe festucae"
            },
            {
                "id":"genome_10",
                "label":"Streptomyces sp. ZS0098"
            },
            {
                "id":"genome_11",
                "label":"Streptomyces sp."
            },
            {
                "id":"genome_12",
                "label":"Streptomyces kitasatoensis"
            },
            {
                "id":"genome_13",
                "label":"Amycolatopsis methanolica"
            },
            {
                "id":"genome_14",
                "label":"Streptacidiphilus oryzae TH49"
            },
            {
                "id":"genome_15",
                "label":"Streptomyces sp. NRRL S-87"
            },
            {
                "id":"genome_16",
                "label":"Nostoc sp. PCC 7120 = FACHB-418"
            },
            {
                "id":"genome_17",
                "label":"FP929039.1"
            },
            {
                "id":"genome_18",
                "label":"GCA_000085225.1_ASM8522v1_genomic"
            },
            {
                "id":"genome_19",
                "label":"Pyrococcus horikoshii OT3"
            },
            {
                "id":"genome_20",
                "label":"Candidatus Prometheoarchaeum syntrophicum"
            },
            {
                "id":"genome_21",
                "label":"Chloracidobacterium sp. 2"
            },
            {
                "id":"genome_22",
                "label":"Haladaptatus sp. F3-133"
            },
            {
                "id":"genome_23",
                "label":"Candidatus Promineofilum breve"
            },
            {
                "id":"genome_24",
                "label":"Candidatus Nitrosocosmicus franklandus"
            }
        ],
        "accession_newick":[],
        "bgc":[
            {
                "acc":0,
                "class":0,
                "id":"AP018533.1.region001"
            },
            {
                "acc":0,
                "class":0,
                "id":"AP018533.1.region002"
            },
            {
                "acc":0,
                "class":0,
                "id":"AP018533.1.region003"
            },
            {
                "acc":0,
                "class":0,
                "id":"AP018533.1.region004"
            },
            {
                "acc":0,
                "class":0,
                "id":"AP018533.1.region005"
            },
            {
                "acc":0,
                "class":0,
                "id":"AP018533.1.region006"
            },
            {
                "acc":0,
                "class":0,
                "id":"AP018533.1.region007"
            },
            {
                "acc":0,
                "class":0,
                "id":"AP018533.1.region008"
            },
            {
                "acc":1,
                "class":0,
                "id":"BGC0000082"
            },
            {
                "acc":2,
                "class":0,
                "id":"BGC0000282"
            },
            {
                "acc":3,
                "class":0,
                "id":"BGC0000324"
            },
            {
                "acc":4,
                "class":0,
                "id":"BGC0000501"
            },
            {
                "acc":3,
                "class":0,
                "id":"BGC0000663"
            },
            {
                "acc":5,
                "class":0,
                "id":"BGC0000833"
            },
            {
                "acc":6,
                "class":0,
                "id":"BGC0000943"
            },
            {
                "acc":7,
                "class":0,
                "id":"BGC0001483"
            },
            {
                "acc":8,
                "class":0,
                "id":"BGC0001543"
            },
            {
                "acc":9,
                "class":0,
                "id":"BGC0002174"
            },
            {
                "acc":10,
                "class":0,
                "id":"BGC0002285"
            },
            {
                "acc":11,
                "class":0,
                "id":"BGC0002293"
            },
            {
                "acc":12,
                "class":0,
                "id":"BGC0002452"
            },
            {
                "acc":13,
                "class":0,
                "id":"BGC0002544"
            },
            {
                "acc":14,
                "class":0,
                "id":"BGC0002656"
            },
            {
                "acc":15,
                "class":0,
                "id":"BGC0002669"
            },
            {
                "acc":16,
                "class":0,
                "id":"BGC0002683"
            },
            {
                "acc":17,
                "class":0,
                "id":"FP929039.1.region001"
            },
            {
                "acc":17,
                "class":0,
                "id":"FP929039.1.region002"
            },
            {
                "acc":17,
                "class":0,
                "id":"FP929039.1.region003"
            },
            {
                "acc":17,
                "class":0,
                "id":"FP929039.1.region004"
            },
            {
                "acc":17,
                "class":0,
                "id":"FP929039.1.region005"
            },
            {
                "acc":17,
                "class":0,
                "id":"FP929039.1.region006"
            },
            {
                "acc":18,
                "class":0,
                "id":"GCA_000085225.1_ASM8522v1_genomic"
            },
            {
                "acc":19,
                "class":1,
                "id":"GCF_000011105.1"
            },
            {
                "acc":20,
                "class":0,
                "id":"GCF_008000775.1"
            },
            {
                "acc":21,
                "class":0,
                "id":"GCF_018304705.1"
            },
            {
                "acc":22,
                "class":2,
                "id":"GCF_026242195.1"
            },
            {
                "acc":23,
                "class":0,
                "id":"GCF_900066015.1"
            },
            {
                "acc":24,
                "class":1,
                "id":"GCF_900696045.1"
            },
            {
                "acc":21,
                "class":1,
                "id":"NZ_CP072636.1.region001"
            },
            {
                "acc":21,
                "class":1,
                "id":"NZ_CP072636.1.region002"
            },
            {
                "acc":21,
                "class":1,
                "id":"NZ_CP072636.1.region003"
            },
            {
                "acc":21,
                "class":3,
                "id":"NZ_CP072636.1.region004"
            },
            {
                "acc":21,
                "class":2,
                "id":"NZ_CP072636.1.region005"
            },
            {
                "acc":21,
                "class":2,
                "id":"NZ_CP072637.1.region001"
            },
            {
                "acc":21,
                "class":1,
                "id":"NZ_CP072637.1.region002"
            },
            {
                "acc":21,
                "class":2,
                "id":"NZ_CP072637.1.region003"
            },
            {
                "acc":24,
                "class":1,
                "id":"NZ_LR216287.1.region001"
            }
        ],
        "classes":[
            {
                "label":"Others"
            },
            {
                "label":"RiPPs"
            },
            {
                "label":"Terpene"
            },
            {
                "label":"PKSother"
            }
        ]
    },
    "networks":[
        {
            "families":[
                {
                    "label":"FAM_00030",
                    "members":[
                        0,
                        5,
                        30
                    ],
                    "mibig":[]
                },
                {
                    "label":"FAM_00036",
                    "members":[
                        1,
                        33,
                        36
                    ],
                    "mibig":[]
                },
                {
                    "label":"FAM_00031",
                    "members":[
                        2,
                        4,
                        6,
                        15,
                        17,
                        25,
                        26,
                        27,
                        28,
                        29,
                        31
                    ],
                    "mibig":[]
                },
                {
                    "label":"FAM_00034",
                    "members":[
                        3,
                        7,
                        9,
                        12,
                        22,
                        23,
                        34
                    ],
                    "mibig":[]
                },
                {
                    "label":"FAM_00020",
                    "members":[
                        8,
                        11,
                        13,
                        16,
                        18,
                        20
                    ],
                    "mibig":[]
                },
                {
                    "label":"FAM_00021",
                    "members":[
                        10,
                        19,
                        21
                    ],
                    "mibig":[]
                },
                {
                    "label":"FAM_00024",
                    "members":[
                        14,
                        24
                    ],
                    "mibig":[]
                }
            ],
            "families_similarity":[
                [
                    [
                        1.0,
                        [
                            1.0,
                            0,
                            0
                        ],
                        [
                            1.0,
                            0,
                            0
                        ]
                    ]
                ],
                [
                    [
                        0.02742183208465576,
                        [
                            0.014094948768615723,
                            30,
                            36
                        ],
                        [
                            0.04987800121307373,
                            1,
                            5
                        ]
                    ],
                    [
                        1.0,
                        [
                            1.0,
                            1,
                            1
                        ],
                        [
                            1.0,
                            1,
                            1
                        ]
                    ]
                ],
                [
                    [
                        0.014918802362499815,
                        [
                            0,
                            2,
                            5
                        ],
                        [
                            0.06968933343887329,
                            5,
                            27
                        ]
                    ],
                    [
                        0.04122884345777107,
                        [
                            0,
                            1,
                            2
                        ],
                        [
                            0.12856149673461914,
                            31,
                            36
                        ]
                    ],
                    [
                        1.0,
                        [
                            1.0,
                            2,
                            2
                        ],
                        [
                            1.0,
                            2,
                            2
                        ]
                    ]
                ],
                [
                    [
                        0.015452878815787179,
                        [
                            0,
                            3,
                            30
                        ],
                        [
                            0.09460967779159546,
                            0,
                            7
                        ]
                    ],
                    [
                        0.03453945829754784,
                        [
                            0,
                            1,
                            3
                        ],
                        [
                            0.09279423952102661,
                            3,
                            36
                        ]
                    ],
                    [
                        0.016280589165625633,
                        [
                            0,
                            2,
                            3
                        ],
                        [
                            0.12481099367141724,
                            28,
                            34
                        ]
                    ],
                    [
                        1.0,
                        [
                            1.0,
                            3,
                            3
                        ],
                        [
                            1.0,
                            3,
                            3
                        ]
                    ]
                ],
                [
                    [
                        0.017427192793952093,
                        [
                            0.0011226534843444824,
                            8,
                            30
                        ],
                        [
                            0.04641997814178467,
                            11,
                            30
                        ]
                    ],
                    [
                        0.02282179395357768,
                        [
                            0,
                            1,
                            11
                        ],
                        [
                            0.0589677095413208,
                            8,
                            36
                        ]
                    ],
                    [
                        0.007419648495587436,
                        [
                            0,
                            2,
                            8
                        ],
                        [
                            0.07641792297363281,
                            11,
                            25
                        ]
                    ],
                    [
                        0.0175971630073729,
                        [
                            0,
                            3,
                            8
                        ],
                        [
                            0.09959632158279419,
                            11,
                            22
                        ]
                    ],
                    [
                        1.0,
                        [
                            1.0,
                            8,
                            8
                        ],
                        [
                            1.0,
                            8,
                            8
                        ]
                    ]
                ],
                [
                    [
                        0.005318091975318061,
                        [
                            0,
                            0,
                            21
                        ],
                        [
                            0.015091121196746826,
                            5,
                            10
                        ]
                    ],
                    [
                        0.029955916934543185,
                        [
                            0,
                            1,
                            10
                        ],
                        [
                            0.055594027042388916,
                            19,
                            33
                        ]
                    ],
                    [
                        0.008808672428131104,
                        [
                            0,
                            2,
                            10
                        ],
                        [
                            0.047811686992645264,
                            21,
                            31
                        ]
                    ],
                    [
                        0.011271550541832334,
                        [
                            0,
                            3,
                            10
                        ],
                        [
                            0.07089012861251831,
                            21,
                            34
                        ]
                    ],
                    [
                        0.03234047028753492,
                        [
                            0,
                            11,
                            21
                        ],
                        [
                            0.1024395227432251,
                            10,
                            13
                        ]
                    ],
                    [
                        1.0,
                        [
                            1.0,
                            10,
                            10
                        ],
                        [
                            1.0,
                            10,
                            10
                        ]
                    ]
                ],
                [
                    [
                        0.006785104672114055,
                        [
                            0,
                            0,
                            14
                        ],
                        [
                            0.020694494247436523,
                            24,
                            30
                        ]
                    ],
                    [
                        0.009238332509994507,
                        [
                            0,
                            1,
                            14
                        ],
                        [
                            0.026157081127166748,
                            14,
                            36
                        ]
                    ],
                    [
                        0.004787854172966697,
                        [
                            0,
                            2,
                            14
                        ],
                        [
                            0.04709237813949585,
                            14,
                            31
                        ]
                    ],
                    [
                        0.00784467373575483,
                        [
                            0,
                            3,
                            14
                        ],
                        [
                            0.04323625564575195,
                            14,
                            34
                        ]
                    ],
                    [
                        0.008320952455202738,
                        [
                            0,
                            11,
                            14
                        ],
                        [
                            0.0574115514755249,
                            11,
                            24
                        ]
                    ],
                    [
                        0.013268421093622843,
                        [
                            0,
                            10,
                            14
                        ],
                        [
                            0.05696779489517212,
                            14,
                            21
                        ]
                    ],
                    [
                        1.0,
                        [
                            1.0,
                            14,
                            14
                        ],
                        [
                            1.0,
                            14,
                            14
                        ]
                    ]
                ]
            ],
            "label":"Others"
        },
        {
            "families":[
                {
                    "label":"FAM_00046",
                    "members":[
                        32,
                        37,
                        46
                    ],
                    "mibig":[]
                },
                {
                    "label":"FAM_00040",
                    "members":[
                        34,
                        40
                    ],
                    "mibig":[]
                },
                {
                    "label":"FAM_00044",
                    "members":[
                        38,
                        39,
                        44
                    ],
                    "mibig":[]
                }
            ],
            "families_similarity":[
                [
                    [
                        1.0,
                        [
                            1.0,
                            32,
                            32
                        ],
                        [
                            1.0,
                            32,
                            32
                        ]
                    ]
                ],
                [
                    [
                        0.045846144358317055,
                        [
                            0,
                            40,
                            46
                        ],
                        [
                            0.14125478267669678,
                            32,
                            34
                        ]
                    ],
                    [
                        1.0,
                        [
                            1.0,
                            34,
                            34
                        ],
                        [
                            1.0,
                            34,
                            34
                        ]
                    ]
                ],
                [
                    [
                        0.002739899688296848,
                        [
                            0,
                            39,
                            46
                        ],
                        [
                            0.009659290313720703,
                            38,
                            46
                        ]
                    ],
                    [
                        0.5,
                        [
                            0,
                            38,
                            40
                        ],
                        [
                            1.0,
                            34,
                            38
                        ]
                    ],
                    [
                        1.0,
                        [
                            1.0,
                            38,
                            38
                        ],
                        [
                            1.0,
                            38,
                            38
                        ]
                    ]
                ]
            ],
            "label":"RiPPs"
        },
        {
            "families":[
                {
                    "label":"FAM_00043",
                    "members":[
                        34,
                        42,
                        43
                    ],
                    "mibig":[]
                },
                {
                    "label":"FAM_00036",
                    "members":[
                        35,
                        36,
                        45
                    ],
                    "mibig":[]
                }
            ],
            "families_similarity":[
                [
                    [
                        1.0,
                        [
                            1.0,
                            34,
                            34
                        ],
                        [
                            1.0,
                            34,
                            34
                        ]
                    ]
                ],
                [
                    [
                        0.14106114705403647,
                        [
                            0,
                            43,
                            45
                        ],
                        [
                            1.0,
                            34,
                            45
                        ]
                    ],
                    [
                        1.0,
                        [
                            1.0,
                            35,
                            35
                        ],
                        [
                            1.0,
                            35,
                            35
                        ]
                    ]
                ]
            ],
            "label":"Terpene"
        },
        {
            "families":[
                {
                    "label":"FAM_00034",
                    "members":[
                        34,
                        41
                    ],
                    "mibig":[]
                },
                {
                    "label":"FAM_00036",
                    "members":[
                        36
                    ],
                    "mibig":[]
                }
            ],
            "families_similarity":[
                [
                    [
                        1.0,
                        [
                            1.0,
                            34,
                            34
                        ],
                        [
                            1.0,
                            34,
                            34
                        ]
                    ]
                ],
                [
                    [
                        0.030148684978485107,
                        [
                            0.0027143359184265137,
                            36,
                            41
                        ],
                        [
                            0.0575830340385437,
                            34,
                            36
                        ]
                    ],
                    [
                        1.0,
                        [
                            1.0,
                            36,
                            36
                        ],
                        [
                            1.0,
                            36,
                            36
                        ]
                    ]
                ]
            ],
            "label":"PKSother"
        }
    ],
    "parameters":"--inputdir input/ --outputdir output_47_cutoffs/ --pfam_dir pfam/ --include_gbk_str A B G F N C --cutoffs 0.1 0.5 1.0",
    "start_time":"07/02/2024 15:39:22"
};
dataLoaded();
